PaypalApp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import CompletePayoutRequest, GetPayoutTransactions,RemovePayout

app_name = 'PaypalApp'

urlpatterns = [
    path('', CompletePayoutRequest, name='payout'),
    path('GetPayouts/', GetPayoutTransactions, name='GetPayouts'),
    path('DelPayout/<str:pk>', RemovePayout, name='DelPayouts'),

]

PaypalProj/urls.py
from django.contrib import admin
from django.urls import path, include
from PaypalApp.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PaypalApp.urls', namespace='PaypalApp'))
]

PaypalApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    Email = models.CharField(max_length=255, default=''),
    Refrence_Id = models.IntegerField(blank=True, null=True)


class transactionsModel(models.Model):

    payout_item_id = models.CharField(max_length=100, default='')
    transaction_id = models.CharField(max_length=100, default='')
    transaction_status = models.CharField(max_length=100, default='')
    currency = models.CharField(max_length=100, default='')
    payout_fee = models.FloatField()
    payout_batch_id =  models.CharField(max_length=100, default='')
    recipient_type = models.CharField(max_length=100, default='')
    recieving_amount = models.FloatField()
    reciever = models.CharField(max_length=100, default='')
    recipient_wallet = models.CharField(max_length=100, default='')
    time_processed = models.CharField(max_length=100, default='')


class Meta:
    model = transactionsModel # model name
    fields = ('__all__')

PaypalApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = '__all__'

PaypalApp/views.py
from curses.ascii import HT
import email
from shlex import quote
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect
from django.contrib import messages
from paypal.standard.forms import PayPalPaymentsForm
import csv
import io
from django.conf import settings
from paypalpayoutssdk.payouts import PayoutsPostRequest
from paypalhttp import HttpError
from paypalhttp.serializers.json_serializer import Json
from paypalpayoutssdk.core import PayPalHttpClient, SandboxEnvironment, LiveEnvironment
from paypalpayoutssdk.payouts import PayoutsGetRequest
from .models import transactionsModel
from django.core import serializers
import json
import re


def GetClient():

    client_id = settings.PAYPAL_CLIENT_ID
    client_secret = settings.PAYPAL_CLIENT_SECRET

    if settings.PAYPAL_TEST:
        environment = SandboxEnvironment(
            client_id=client_id, client_secret=client_secret
        )
    else:
        environment = LiveEnvironment(
            client_id=client_id, client_secret=client_secret
        )

    client = PayPalHttpClient(environment)

    return client


def PayoutBody(request, io_string):

    mydict = list()
    recipient_type = ''

    for data in csv.reader(io_string, delimiter=',', quotechar="|"):
        regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
        if(re.search(regex, data[0])):
            recipient_type = "EMAIL"
            receiver = data[0]
        else:
            recipient_type = "PHONE"
            receiver = data[0]
        dict = {
            # Make a list of dictionary to store the dynamic  variable into the json
            "recipient_type": recipient_type, "amount":
            {
                "value": data[2],
                "currency": data[1]
            },
            "note": "Thanks for your patronage!",
            "sender_item_id": "201403140001",
            "receiver": receiver
        }
        mydict.append(dict)
    body = {
        "sender_batch_header": {
            "sender_batch_id": "15240864949",
            "email_subject": "This email is related to simulation"
        },
        "items": mydict    # Call List of dictionary
    }

    return body


def MakePayoutRequest(body):
    request = PayoutsPostRequest()  # Make Payout POST request
    request.request_body(body)
    return request


def GetPayout(response, client):

    # Get Payout Batch id from response
    payout_item_id = response.result.batch_header.payout_batch_id

    ###### Make a request from Batch Id ###########
    requestt = PayoutsGetRequest(payout_item_id)

    payout_response = client.execute(requestt)  # execute request
    response = payout_response.result  # Payout Response from Payout Batch id
    return response


def CompletePayoutRequest(request):
    client = GetClient()
    PayoutId = list()

    if request.method != 'POST':
        list_id = request.session.get('ids')
        if list_id is None:
            allRecords = []
        else:
            allRecords = transactionsModel.objects.filter(
                id__in=list_id).values()
        context = {
            'allRecords': allRecords
        }
        # request.session['ids'] = []
        return render(request, "Payment/file.html", context)
    else:
        csv_file = request.FILES['file']
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'This is not a Csv File')
        return redirect('/')

    ########### read csv ###############################

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)

    ########### read csv ###############################

    body = PayoutBody(request, io_string)

    # call to make the request body
    # call to MakePayout customised function

    PayOutRequest = MakePayoutRequest(body)

    try:
        # Make Api call to get Paypout Batch Id
        response = client.execute(PayOutRequest)
        # Get Response from   Batch Id
        Payout = GetPayout(response, client)

        for payout_data in Payout['items']:
            # Submit Transactions data into the database
            id = CreateTransactions(request, payout_data)
            PayoutId.append(id)
        request.session['ids'] = PayoutId
        messages.success(request, ("Transaction created"))

        return redirect('/')
    except IOError as ioe:
        print(ioe)
        if isinstance(ioe, HttpError):
            print(ioe.status_code)
        else:
            print(ioe)


def CreateTransactions(request, payout_data):  # Match Payout rows to the DB table

    created = transactionsModel(
        payout_item_id=payout_data['payout_item_id'],
        # transaction_id=payout_data['transaction_id'],
        transaction_status=payout_data['transaction_status'],
        currency=payout_data['payout_item_fee']['currency'],
        payout_fee=payout_data['payout_item_fee']['value'],
        payout_batch_id=payout_data['payout_batch_id'],
        recieving_amount=payout_data['payout_item']['amount']['value'],
        reciever=payout_data['payout_item']['receiver'],
        recipient_wallet=payout_data['payout_item']['recipient_wallet'],
        time_processed=payout_data['time_processed'],
        recipient_type=payout_data['payout_item']['recipient_type']
    )
    created.save()
    id = created.pk
    return id


def GetPayoutTransactions(request):
    Payouts = transactionsModel.objects.filter().values()
    if Payouts:
        context = {
            "Payoutsdata": Payouts,
            "instance": request.session.get('instance')
        }
    else:
        context = {
            "Payoutsdata": [],
            "instance": []
        }
        messages.error(request, 'No Transactions yet')

    return render(request, 'Payment/PayoutTransactions.html', context)


def RemovePayout(request, pk):
    instance = transactionsModel.objects.filter(id=pk).delete()
    if instance:
        request.session['instance'] = instance
        messages.success(request, 'Transactions Deleted successfully')
    else:
        request.session['instance'] = ''
        messages.error(request, 'Some Error occured')
    return redirect('PaypalApp:GetPayouts')

templates/Payment/PayoutTransactions.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>Payout Transactions</title>
</head>

<body>
    <div class="container">
        <div class="text-center mt-5">
            <h3>Payout Transactions</h3>
        </div>
        <a class="btn btn-primary" href="{% url 'PaypalApp:payout' %}">Go Back</a>
       {% if instance %}
       {% for message in messages %}
       <div class="container-fluid p-0 mt-5">
           <div class="alert {{ message.tags }} alert-dismissible" role="alert">
               <button type="button" class="close btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
               </button>
               {{ message }}
           </div>
       </div>
       {% endfor %}
       {% endif %}
        {% if Payoutsdata %}
        <div class="table-responsive mt-5 mb-5">
            <table class="table table-success">
                <thead>
                    <tr>
                        <th scope="col">Sr.No</th>
                        <th scope="col">PAYOUT ID</th>
                        <th scope="col">TRANSACTION ID</th>
                        <th scope="col">TRANSACTION STATUS</th>
                        <th scope="col">CURRENCY</th>
                        <th scope="col">PAYOUT FEE</th>
                        <th scope="col">PAYOUT BATCH ID</th>
                        <th scope="col">RECEIVER</th>
                        <th scope="col">RECIPIENT WALLET</th>
                        <th scope="col">TIME PROCESSED</th>
                        <th scope="col">RECIPIENT TYPE</th>
                        <th scope="col"> Action </th>
                    </tr>
                </thead>
                <tbody>

                    {% for data in Payoutsdata %}
                    <tr class="nr">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{data.payout_item_id}}</td>
                        <td>{{data.transaction_id}}</td>
                        <td>{{data.transaction_status}}</td>
                        <td>{{data.currency}}</td>
                        <td>{{data.payout_fee}}</td>
                        <td>{{data.payout_batch_id}}</td>
                        <td>{{data.reciever}}</td>
                        <td>{{data.recipient_wallet}}</td>
                        <td>{{data.time_processed}}</td>
                        <td>{{data.recipient_type}}</td>
                        <td><button class="btn-close close close_btn" id="endpoint-url-div"
                                url="{% url 'PaypalApp:DelPayouts' data.id %}" onclick="GetUrl(this)"
                                data-bs-dismiss="alert" aria-label="Close" type="button" value="{{data.id}}"></button>
                        </td>
                    </tr>
                    {% endfor %}


                </tbody>
            </table>

        </div>

        {% elif messages %}
        {% for message in messages %}
        <div class="container-fluid p-0 mt-5">
            <div class="alert {{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </button>
                {{ message }}
            </div>
        </div>
        {% endfor %}
        {% endif %}

      
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
<script>
    $('.close').click(function () {
        $("div.alert").hide();

    });
</script>

<script>
    function GetUrl(a) {
        var url = $(a).attr('url')
        setTimeout(function () {
            window.location = url
        }, 0);
    }
</script>

</html>

templates/Payment/file.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>Upload Csv</title>
</head>

<body>
    <div class="container">

        <div class="col">
        </div>
        {% for message in messages %}
        <div class="container-fluid p-0 mt-5">
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </button>
                {{ message }}
            </div>
        </div>
        {% endfor %}
        <a class="btn btn-success mt-5" href="{% url 'PaypalApp:GetPayouts' %}">Show Transactions</a>
        <form action="{% url 'PaypalApp:payout' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label for="Uplaod CSV" class="form-label">Uplaod CSV</label>
                <input type="file" class="form-control" id="" name="file" required>
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
        </form>


        <div class="col">
        </div>

        {% if allRecords %}
        <div class="table-responsive mt-5">
            <table class="table table-success">
                <thead>
                    <tr>
                        <th scope="col">Sr.No</th>
                        <th scope="col">PAYOUT ID</th>
                        <th scope="col">TRANSACTION ID</th>
                        <th scope="col">TRANSACTION STATUS</th>
                        <th scope="col">CURRENCY</th>
                        <th scope="col">PAYOUT FEE</th>
                        <th scope="col">PAYOUT BATCH ID</th>
                        <th scope="col">RECEIVER</th>
                        <th scope="col">RECIPIENT WALLET</th>
                        <th scope="col">TIME PROCESSED</th>
                        <th scope="col">RECIPIENT TYPE</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in allRecords %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{data.payout_item_id}}</td>
                        <td>{{data.transaction_id}}</td>
                        <td>{{data.transaction_status}}</td>
                        <td>{{data.currency}}</td>
                        <td>{{data.payout_fee}}</td>
                        <td>{{data.payout_batch_id}}</td>
                        <td>{{data.reciever}}</td>
                        <td>{{data.recipient_wallet}}</td>
                        <td>{{data.time_processed}}</td>
                        <td>{{data.recipient_type}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

<script>
    $('.close').click(function () {
        $("div.alert").hide();

    });
</script>

</html>